# Generated by Django 5.1.4 on 2025-01-18 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0004_alter_reminder_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='type',
            field=models.CharField(max_length=50),
        ),
    ]
