# Generated by Django 5.1.4 on 2025-01-18 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0005_alter_reminder_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='color',
            field=models.IntegerField(default=0),
        ),
    ]
