# Generated by Django 5.1.4 on 2025-01-18 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0007_remove_reminder_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='icon',
        ),
    ]
