# Generated by Django 5.1.4 on 2025-01-18 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0008_remove_reminder_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='period',
            field=models.CharField(default='صباحاً', max_length=10),
        ),
    ]
